# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa89e04d189310252fa40657678f4095b6f8e257c0939ce0c2702ddad76faad08dc1594b6ab2e1837dcb0765907442d3ac71318ecdf736619914240e3676bd2b

test:
  secret_key_base: 4593e56315a759e0ba567e7c538366fc2ce1b9d501b3ea680a9fe396d23a174782f1c7fba77ca408a59cd6cc82314abc4e840d9136dc124b0539bb0d25f601a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
